kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager-binding
  namespace: rbac-demo-namespace
subjects:
- kind: User
  name: user01
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
