apiVersion: v1
kind: Pod
metadata:
  name: rogue-nginx-container
  namespace: k8s-demo
spec:
  containers:
  - name: rogue-nginx-container
    image: nginx
    resources:
      limits:
        memory: "1.5Gi"
      requests:
        memory: "256Mi"
