apiVersion: v1
kind: Pod
metadata:
  name: config-map-demo
  namespace: k8s-demo
spec:
  containers:
    - name: configmap-demo-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: demo-config-map
              # Specify the key associated with the value
              key: special.how
  restartPolicy: Never
