spring:
  profiles: dev
  h2:
    console:
      enabled: true

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

spring.jpa:
    hibernate.ddl-auto: create-drop

contact.service:
  name: 'dev profile:'
